### ISSUE TITLE
building for the picoW

### ISSUE THREAD

**Issue by luisqcosta** [RealByron/PicoW-Intex-PureSpa#1]
Hi! Congratulations on the project! I am bringing to life my intex spa, just like yours.

Would it be possible to have some short directions on how to  upload\load everything in the pico?

Also, the home assistant API needs changing if i am correct?

I am sorry  for this, it is my first time with the Pico!

**Comment by cyb3rfox** [comment]
Just replace the external_components section with the following and it will build directly on your esphome.

external_components:
  - source:
      type: git  
      url: https://github.com/RealByron/PicoW-Intex-PureSpa
    components: [purespa]

**Comment by aldoagosta** [comment]
Hello guys, I am trying to debug the project platformio.ini without success. 
The board is a brand new Raspberry PI Pico W (the same shown in the project pics)
Any kind advice from your side?

Many thanks in advance

Regards 

Aldo

here the log:

LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ off, Compatibility ~ soft
Found 30 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ArduinoJson @ 6.21.3
Building in debug mode
Linking .pio\build\rp2040-pico-arduino\firmware.elf
c:/users/aldo/.platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/12.3.0/../../../../arm-none-eabi/bin/ld.exe: warning: .pio\build\rp2040-pico-arduino\firmware.elf has a LOAD segment with RWX permissions
c:/users/aldo/.platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/12.3.0/../../../../arm-none-eabi/bin/ld.exe: .pio\build\rp2040-pico-arduino\libFrameworkArduino.a(main.cpp.o): in function `main':
C:\Users\aldo\.platformio\packages\framework-arduinopico\cores\rp2040/main.cpp:144: undefined reference to `setup'
c:/users/aldo/.platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/12.3.0/../../../../arm-none-eabi/bin/ld.exe: C:\Users\aldo\.platformio\packages\framework-arduinopico\cores\rp2040/main.cpp:146: undefined reference to `loop'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\rp2040-pico-arduino\firmware.elf] Error 1
======================================================================================================================================= [FAILED] Took 3.30 seconds =======================================================================================================================================

Environment          Status    Duration
-------------------  --------  ------------
rp2040-pico-arduino  FAILED    00:00:03.300
================================================================================================================================== 1 failed, 0 succeeded in 00:00:03.300 ==================================================================================================================================
 *  The terminal process "C:\Users\aldo\.platformio\penv\Scripts\platformio.exe 'debug'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by luisqcosta** [comment]
You guys managed to get it to work?

**Comment by jonpeltier11** [comment]
Hello, I am certainly no software dev but I did get this project to work. This project is not compiled in the usual manner. It is completely done inside of ESPhome (dev).  From what I understand you have to use the developer version of ESP home at least you did when I completed this project. On my initial upload to the Pico W, it had to be done through a USB cable connected to whatever computer you're accessing home assistant on. After that, any further updates can be done over the air. Regular release ESP home does program ESP32 boards and such but from what I understand, Pico W's have to be uploaded to from developer version. You're going to want to make sure you have a USBA micro cable that carries data. If you want to be able to monitor the Pico W internal chip sensor, you simply add three lines to your yaml see attached. 
![Screenshot_20240623_151732_Chrome Beta](https://github.com/RealByron/PicoW-Intex-PureSpa/assets/82741127/cf5d8226-f7bf-41e0-9bb0-083a9068b3df)

**Comment by RealByron** [comment]
> You guys managed to get it to work?

I did add some installation steps in readme
