### ISSUE TITLE
How did you build the connectors and more

### ISSUE THREAD

**Issue by aldoagosta** [RealByron/PicoW-Intex-PureSpa#3]
Hello, I really like your project and I need to build it up quite soon! 
I would kindly ask how you built up the intex connectors. 3D printing I guess... If so, where I can find the project files? Once printed, how did you make the metal pins to put into the plastic connectors? They are supposed to be both male and female depending on the side.

Last, which tool did you use for programming the RB Pico board?

Many thanks.

Regards

Aldo

**Comment by Elektroarzt** [comment]
Hi Aldo ... if you look for a printed solution, maybe my [printables project](https://www.printables.com/de/model/509289-intex-purespa-whirlpool-controller-electromechanic) is interesting for you. Here you find answers to your questions. It is based on ESP8266, but the mechanics will likely fit for RealByron's hardware design.

**Comment by aldoagosta** [comment]
for Intex connectors I also found this 3D printing project and related files:
https://www.thingiverse.com/thing:4130911/comments

Concerning the pins, Farnell items 1248239 (926882-3) and 1248241 (926883-3) can be used as well
https://it.farnell.com/amp-te-connectivity/926882-3/contacts-bronze-phosphoreux-0/dp/1248239
https://it.farnell.com/amp-te-connectivity/926882-3/contacts-bronze-phosphoreux-0/dp/1248241

I'll keep you posted on progress. 
I will come back to you for module programming issues if any.

Many thanks 

Bye

Aldo
