### ISSUE TITLE
Setting climate mode to 'off' turns off heater, but does not reflect in HA

### ISSUE THREAD

**Issue by peetipablo** [RealByron/PicoW-Intex-PureSpa#5]
Hey there, thank you so much for this repo, I was able to follow your instructions to get the rpi pico w working as a remote and in HA.  

There is one hiccup I can't seem to correct - when I change the hot tube climate entity to 'off' in Home Assistant, it does in fact turn the heater of the spa off, but in HA after a second the mode incorrectly reverts back to showing 'Heat'.  The climate entity will then only correctly show 'off' when you try to change the temperature.  

The same behavior occurs when switching mode to 'heat' - the climate entity still shows 'off' until you change the target temperature, when it will then show 'on'.

Any idea how this can be corrected?

**Comment by RealByron** [comment]
fix !

**Comment by peetipablo** [comment]
Thank you, looks like it works perfectly now!

**Comment by RealByron** [comment]
Great 😊
